language: ruby
env:
 # 4.1 uses sprockets 2
 - "RAILS_VERSION=4.1.0"
 # 4.2 uses sprockets 3
 - "RAILS_VERSION=4.2.0"
rvm:
 - 2.2
 - 2.3
 - 2.4
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: b9EXJl8sjZwHdZOLc9ypwknQh8B4jz0xDOIDhaxLdo7/17Hzim5uz9aWBMYyIh5tPk/5gXGkWIEut2+RlgnjmMPDhPiXOdgAIUyGXepUS9Vjww1CxhTzIb5mCSq4g597s1KXdLSvqu5EXWc4roDYuzvAcI04BWpLUBqLAiWVMKPZlzuQQuQKonuY67Fr64kvxzULc7rhnbMO+LAiNcv8Rdps9Q4AdV75Ifmhj4XC7G3QuHfP0IFUGatBJEK5tJDLK3Qonxj0UJ5uG7wrCmlj/GWYTm1OG4KEvdkXGN5c1ZttyKXUxuKsrKoD4zh/RtHH5DYvJbYSQMWrig5eJKqFVleX4HU4n9RsAFdCFMYsdahpmIBgGLH+KymWT1JT9YCFE0CuG58Al3EZM8AxnVFlHL5OGDl6kyDk17bkw/4WC/dRtPTjJyYJL0PoTabaXDHbfZM810zxNVJyUHmyRNIVXv7V8dAAgWjtcg7DCw70VmJyahUNPv9pda9eRNPfUgip8L4Qb6buiVgm+QCI627vLxzbhJyHAL19ubh/NTuPdx7qYTpF4Y6Tw5bprpDAkW86VlzkJjTW8d5E6c3K88RYzP1I+pqqGjXOjq5Dd/o1rop+Bqkvfa2hJw4WPRDiZuioS3qOW/2E7pKyXuhpJKuA1JaV/ddg9IUpbla8bFCQp88=
  gem: web-components-rails
  on:
    tags: true
    repo: uniite/web-components-rails
